### ISSUE TITLE
Category 和 Item 的关系

### ISSUE THREAD

**Issue by linwenjun** [bmeritter/201-nodejs-web#1]
为什么是Category 持有 Item 而不是 Item 持有 Category ？
如果非要让你做成Item 持有 Category，请给出至少两个理由

**Comment by bmeritter** [comment]
如果让 Item 持有 Category，那么根据不同的标准，一个 Item 可能存在于不同的 Category 中，因此我觉得是 Category 持有 Item

**Comment by linwenjun** [comment]
回答问题的时候请分一下类如下面这种形式
为什么是Category 持有 Item 而不是 Item 持有 Category ？
```
因为...
```

如果非要让你做成Item 持有 Category，请给出至少两个理由
```
1. 我们购物场景是看具体商品多，而不是看分类关系多
2. 商品分类有层级关系，电器包含电视机，某台电视机即属于电视机，也属于电器，这种关系如果用Category 持有 Item 做很麻烦
```

**Comment by bmeritter** [comment]
明白了
